---
- name: Update any Linux system
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    # -----------------------------------------
    # Debian/Ubuntu - APT
    # -----------------------------------------
    - name: Update Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

    # -----------------------------------------
    # RHEL/CentOS/Rocky/Alma - YUM/DNF
    # -----------------------------------------
    - name: Update RHEL-based systems
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    # -----------------------------------------
    # SUSE / openSUSE
    # -----------------------------------------
    - name: Update SUSE-based systems
      zypper:
        name: "*"
        state: latest
      when: ansible_os_family == "Suse"

    # -----------------------------------------
    # Arch Linux
    # -----------------------------------------
    - name: Update Arch Linux systems
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Archlinux"

    # -----------------------------------------
    # Optional: Reboot if required
    # -----------------------------------------
    - name: Reboot if required
      reboot:
        msg: "Rebooting after system update"
        reboot_timeout: 600
      when: ansible_reboot_required | default(false)
