---
- name: Update any Linux system and show updated packages
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    updated_packages: []

  tasks:

    # =======================================================
    # Debian / Ubuntu (APT)
    # =======================================================
    - name: Update APT cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade APT packages
      apt:
        upgrade: full
      register: apt_upgrade
      when: ansible_os_family == "Debian"

    - name: Extract updated package list (Debian/Ubuntu)
      set_fact:
        updated_packages: "{{ apt_upgrade.stdout_lines | default([]) }}"
      when: apt_upgrade is defined

 
    # =======================================================
    # Show Updated Packages
    # =======================================================
    - name: Show updated packages
      debug:
        msg: "{{ updated_packages | default([]) }}"

    # =======================================================
    # Reboot if required
    # =======================================================
    - name: Reboot if required
      reboot:
        msg: "Rebooting after updates"
        reboot_timeout: 600
      when: ansible_reboot_required | default(false)

